-- Add new columns to masjid table
ALTER TABLE masjid ADD COLUMN IF NOT EXISTS telepon VARCHAR(255);
ALTER TABLE masjid ADD COLUMN IF NOT EXISTS email VARCHAR(255);
ALTER TABLE masjid ADD COLUMN IF NOT EXISTS ketua_pengurus VARCHAR(255);
ALTER TABLE masjid ADD COLUMN IF NOT EXISTS countdown_duration INTEGER DEFAULT 600;
